#include "L1Ntuple.h"
#include "hist.C"
#include "Style.C"
#include "TMath.h"
#include "TMultiGraph.h"
#include <TGraphAsymmErrors.h>
#include <TF1.h>
#include "TLegend.h"

// --------------------------------------------------------------------
//                       L1EnergySumAnalysis macro definition
//
//    macro automatically generated by GenerateMacro.sh script
//    author           : bm409
//    creation date    : Fri Aug 13 15:14:51 CEST 2010
//    last update date :
//    description      :
//
// --------------------------------------------------------------------

class L1EnergySumAnalysis : public L1Ntuple
{
  public :

    //constructor
  L1EnergySumAnalysis(std::string filename) : L1Ntuple(filename) {}
  L1EnergySumAnalysis() {}
  ~L1EnergySumAnalysis() {}
  virtual void BookHistos();
  bool PassTrig(int ib);
  // TCanvas GetCanvas(std::string canvasName);
    //main function macro : arguments can be adpated to your need
  void run(Long64_t nevents, TString fOut);

  private :
  TH2D *ResolutionHistoET, *ResolutionHistoHT, *MetHisto, *RecoVsL1SumEt, *RecoVsL1Met, *MhtHisto, *RecoVsL1HT, *RecoVsL1Mht;


  TH1D *MHT_30U;
  TH1D *MHT_20U;
  TH1D *MET_70U;
  TH1D *MET_30U;
  TH1D *MET_20U;
  TH1D *MET_12U;
  TH1D *SumEt_100U;
  TH1D *SumEt_60U;
  TH1D *HT_200U;
  TH1D *HT_100U;
  TH1D *HT_75U;
  TH1D *HT_75U_Bit;
  TH1D *HT_50U;
  TH1D *METReference;
  TH1D *MHTReference;
  TH1D *SumEtReference;
  TH1D *HTReference;
  TH1D *L1Ht;
  TH1D *L1mHt;
  TH1D *L1Et;  //your private methods can be declared here
  TH1D *L1mEt;

};


void L1EnergySumAnalysis::BookHistos() {

  ResolutionHistoET = new TH2D("SumEt reconstuction","",80,-2.0,2.0, 300,0.,300.);
  MetHisto = new TH2D("Met reconstuction","",80,-2.,2., 300,0.,300.);
  RecoVsL1Met = new TH2D("Reco Vs L1 MET","",300,-2.0,2.0,300,0.,300.);
  RecoVsL1SumEt = new TH2D("Reco Vs L1 SumEt","",300,0.,300.,300,0.,300.);

  ResolutionHistoHT = new TH2D("HT reconstuction","",80,-2.,2., 300,0.,300.);
  MhtHisto = new TH2D("Mht reconstuction","",80,-2.,2., 300,0.,300.);
  RecoVsL1Mht = new TH2D("Reco Vs L1 MHT","",300,0.,300.,300,0.,300.);
  RecoVsL1HT = new TH2D("Reco Vs L1 HT","",300,0.,300.,300,0.,300.);




  MHT_30U = new TH1D("MHT 30 Pass","", 50,0.,300.);
  MHT_20U = new TH1D("MHT 20 Pass","", 50,0.,300.);
  MET_70U = new TH1D("MET 70 Pass","", 50,0.,300.);
  MET_30U = new TH1D("MET 30 Pass","", 50,0.,300.);
  MET_20U = new TH1D("MET 20 Pass","", 50,0.,300.);
  MET_12U = new TH1D("MET 11 Pass","", 50,0.,300.);
  SumEt_100U = new TH1D("ET 100 Pass","", 50,0.,100.);
  SumEt_60U = new TH1D("ET 60 Pass","", 50,0.,100.);
  HT_200U = new TH1D("HT 200 Pass","", 50,0.,300.);
  HT_100U = new TH1D("HT 100 Pass","", 50,0.,300.);
  HT_75U = new TH1D("HT 75 Pass","", 50,0.,300.);
  HT_75U_Bit = new TH1D("HT 75 Pass With Bit","", 50,0.,300.);
  HT_50U = new TH1D("HT 50 Pass","", 50,0.,300.);
  METReference = new TH1D("METReference","", 50,0.,300.);
  MHTReference = new TH1D("MHTReference","", 50,0.,300.);
  SumEtReference = new TH1D("SumEtReference","", 50,0.,100.);
  HTReference = new TH1D("HTReference","", 50,0.,300.);
  L1Ht  = new TH1D("L1HT","",1000,0.,1000);
  L1mHt = new TH1D("L1MHT","",1000,0.,1000);
  L1Et  = new TH1D("L1Et","",1000,0.,1000);
  L1mEt = new TH1D("L1MET","",1000,0.,1000);




}

// TCanvas GetCanvas(std::string canvasName){
//   TCanvas *a = new TCanvas(canvasName,canvasName,800,800);
//   return a;
// }


bool L1EnergySumAnalysis::PassTrig(int ib) {
  if(ib<64) { if((gt_->tw1[2]>>ib)&1) { return true; } else return false; }
  if(ib<128) { if((gt_->tw2[2]>>(ib-64))&1) { return true;} else return false;}
  else { if((gt_->tt[2]>>(ib-1000))&1) { return true;} else return false;}
}

// --------------------------------------------------------------------
//                             run function
// --------------------------------------------------------------------
void L1EnergySumAnalysis::run(Long64_t nevents,TString fOut)
{
  //load TDR style
  setTDRStyle();
  BookHistos();
  TFile *theFile = new TFile(fOut, "RECREATE");
  theFile->cd();
  int bx = 2;
  //number of events to process
  if (nevents==-1 || nevents>GetEntries()) nevents=GetEntries();
  std::cout << nevents << " to process ..." << std::endl;

  //loop over the events
  for (Long64_t i=0; i<nevents; i++)
  {
      //load the i-th event
    Long64_t ientry = LoadTree(i); if (ientry < 0) break;
    GetEntry(i);
  bool selection = false;
  //if(!selection) continue;
     bool minbias = std::find(event_->hlt.begin(),event_->hlt.end(),"HLT_L1Tech_BSC_minBias_threshold1_v1")!=event_->hlt.end();
 //HLT_L1Tech_BSC_minBias
//HLT_L1Tech_BSC_minBias_threshold1_v1
    if(!minbias) continue;

      //process progress
    if(i!=0 && (i%10000)==0)
      std::cout << "- processing event " << i << "\r" << std::flush;
    double wgt=1.;
    // if(!PassTrig(1040) || !PassTrig(1041)) continue; // check the event passes min bias triggers
    //cout  << " Which lumi section our event is in " << event_->lumi << " Run Number: " << event_->run <<endl;
//Event Selection
  // if(recoMet_->ecalFlag>3) continue;
  // if(recoMet_->recoMet_->hcalFlag != 0) continue;
    // if ( !((gt_->tt[2]>>40 ) & 0x1) && !((gt_->tt[2]>>41 ) & 0x1) ) continue;
// Make a new HT collection
    double flyHT = 0.;
    for(size_t j = 0; j < recoJet_->etCorr.size(); ++j)
    {
      if( recoJet_->etCorr[j] > 40. && fabs(recoJet_->eta[j]) < 3.){
        flyHT += recoJet_->etCorr[j];
      }
    }

    double  ResolutionET = ( l1extra_->et - recoMet_->sumEt  ) / recoMet_->sumEt;
    double  ResolutionHT = ( l1extra_->ht - flyHT  ) / flyHT;

    double MetReso = ( l1extra_->met - recoMet_->met ) / recoMet_->met;
    double MhtReso = ( l1extra_->mht - recoMet_->mHt ) / recoMet_->mHt;

    ResolutionHistoET->Fill(  ResolutionET ,recoMet_->sumEt , wgt );

    ResolutionHistoHT->Fill( ResolutionHT, flyHT,wgt );

    MetHisto->Fill( MetReso, recoMet_->met, wgt );

    MhtHisto->Fill( MhtReso, recoMet_->mHt, wgt );

    RecoVsL1Met->Fill( recoMet_->met, l1extra_->met, wgt );

    RecoVsL1HT->Fill( flyHT, l1extra_->ht, wgt );

    RecoVsL1Mht->Fill( recoMet_->mHt, l1extra_->mht, wgt );



      HTReference->Fill( flyHT ,wgt);
      if( l1extra_->ht > 50.){ HT_50U->Fill( flyHT ,wgt); }
      if( l1extra_->ht > 100.){ HT_100U->Fill( flyHT ,wgt); }
      if( l1extra_->ht > 200.){ HT_200U->Fill( flyHT ,wgt); }
      if( l1extra_->ht > 75.){ HT_75U_Bit->Fill(flyHT,wgt); }
      if( l1extra_->ht > 75. ){HT_75U->Fill(flyHT, wgt); }
      L1Ht->Fill(l1extra_->ht,wgt);
      L1mHt->Fill(l1extra_->mht,wgt);
      L1Et->Fill(l1extra_->et,wgt);
      L1mEt->Fill(l1extra_->met,wgt);


      SumEtReference->Fill( recoMet_->sumEt ,wgt);
      if( l1extra_->et > 60.) { SumEt_60U->Fill( recoMet_->sumEt ,wgt);}
      if( l1extra_->et > 100.) { SumEt_100U->Fill( recoMet_->sumEt,wgt);}

      MHTReference->Fill( recoMet_->mHt ,wgt);
      if(l1extra_->mht > 20.){ MHT_20U->Fill(recoMet_->mHt,wgt);}
      if(l1extra_->mht > 30.) { MHT_30U->Fill(recoMet_->mHt,wgt);}

      METReference->Fill( recoMet_->met ,wgt);
      if( recoMet_->met >12. ) { MET_12U->Fill(recoMet_->met,wgt);}
      if( recoMet_->met >20. ) { MET_20U->Fill(recoMet_->met,wgt);}
      if( recoMet_->met >30. ) { MET_30U->Fill(recoMet_->met,wgt);}
      if( recoMet_->met >70. ) { MET_70U->Fill(recoMet_->met,wgt);}


  }

  gStyle->SetOptTitle(0);

  TCanvas *c1 = new TCanvas("DrawMe","somecanvas",800,800);
  c1->cd();
  ResolutionHistoHT->Draw("9HIST");
  ResolutionHistoHT->Write();
  c1->cd();
  c1->Clear();
  ResolutionHistoET->Draw("9HIST");
  ResolutionHistoET->Write();
  c1->cd();
  c1->Clear();
  MetHisto->Draw("9HIST");
  MetHisto->Write();
  c1->cd();
  c1->Clear();
  MhtHisto->Draw("9HIST");
  MhtHisto->Write();
  c1->cd();
  c1->Clear();
  RecoVsL1Met->Draw("9HIST");
  RecoVsL1Met->Write();
  c1->cd();
  c1->Clear();
  RecoVsL1HT->Draw("9HIST");
  RecoVsL1HT->Write();
  c1->cd();
  c1->Clear();
  RecoVsL1Mht->Draw("9HIST");
  RecoVsL1Mht->Write();
  c1->cd();
  c1->Clear();
  TH1D *profileResolutionHistoET = ResolutionHistoET->TH2D::ProfileY("ProfileETresolution",0,-1,"e");
  profileResolutionHistoET->Draw("o s");
  profileResolutionHistoET->Write();
  c1->cd();
  c1->Clear();
  TH1D *profileResolutionHistoHT = ResolutionHistoHT->TH2D::ProfileY("ProfileResolutioHT",0,-1,"e");
  profileResolutionHistoHT->Draw("o s");
  profileResolutionHistoHT->Write();
  c1->cd();
  c1->Clear();
  TH1D *profileMhtHisto = MhtHisto->TH2D::ProfileY("ProfileMhtHisto",0,-1,"e");
  profileMhtHisto->Draw("o s");
  profileMhtHisto->Write();
  c1->cd();
  c1->Clear();
  TH1D *profileMetHisto = MetHisto->TH2D::ProfileY("ProfileMetHisto",0,-1,"e");
  profileMetHisto->Draw("o s");
  profileMetHisto->Write();
  c1->cd();
  c1->Clear();

  TMultiGraph *HtTurnOnCurves = new TMultiGraph("HT TurnOnCurves", "HtTurnonCurves");
  TGraphAsymmErrors *HT50Uturnon = new TGraphAsymmErrors();
  TGraphAsymmErrors *HT75Uturnon = new TGraphAsymmErrors();
  TGraphAsymmErrors *HT100Uturnon = new TGraphAsymmErrors();
  TGraphAsymmErrors *HT200Uturnon = new TGraphAsymmErrors();

  HT50Uturnon->BayesDivide(HT_50U, HTReference);
  HT50Uturnon->SetMarkerStyle(20);
  HT50Uturnon->SetLineColor(2);
  HT50Uturnon->SetMarkerColor(2);
  HT75Uturnon->BayesDivide(HT_75U, HTReference);
  HT75Uturnon->SetMarkerStyle(25);
  HT75Uturnon->SetLineColor(2);
  HT75Uturnon->SetMarkerColor(2);
  HT100Uturnon->BayesDivide(HT_100U, HTReference);
  HT100Uturnon->SetMarkerStyle(21);
  HT100Uturnon->SetLineColor(6);
  HT100Uturnon->SetMarkerColor(6);
  HT200Uturnon->BayesDivide(HT_200U, HTReference);
  HT200Uturnon->SetMarkerStyle(22);
  HT200Uturnon->SetLineColor(7);
  HT200Uturnon->SetMarkerColor(7);

  HtTurnOnCurves->Add(HT50Uturnon ,"lp");
  HtTurnOnCurves->Add(HT75Uturnon ,"lp");
  HtTurnOnCurves->Add(HT100Uturnon ,"lp");
  HtTurnOnCurves->Add(HT200Uturnon ,"lp");
 gPad->SetGridx(); gPad->SetGridy();

  HtTurnOnCurves->Draw("a p");
  HtTurnOnCurves->GetXaxis()->SetTitle("H_{T} GeV");
  HtTurnOnCurves->GetYaxis()->SetTitle("Efficiency");

  TLegend *leg  = new TLegend(0.2,0.8,.4,.9, "legend");

  leg->AddEntry(HT50Uturnon, "HTT50","l P");
  leg->AddEntry(HT75Uturnon,"HTT75","l P");
  leg->AddEntry(HT100Uturnon,"HTT100","l P");
  leg->AddEntry(HT200Uturnon,"HTT200","l P");

  leg->Draw();
  c1->Write();
  c1->cd();
  c1->Clear();
  leg->Clear();

  TMultiGraph *SumEtTurnOnCurves = new TMultiGraph("SumEt Turn On Curves", "SumET Turn On Curves");
  TGraphAsymmErrors *SumEt60Uturnon = new TGraphAsymmErrors();
  TGraphAsymmErrors *SumEt100Uturnon = new TGraphAsymmErrors();
  SumEt60Uturnon->BayesDivide(SumEt_60U, SumEtReference);
  SumEt60Uturnon->SetMarkerStyle(20);
  SumEt60Uturnon->SetLineColor(2);
  SumEt60Uturnon->SetMarkerColor(2);
  SumEt100Uturnon->BayesDivide(SumEt_100U, SumEtReference);
  SumEt100Uturnon->SetMarkerStyle(21);
  SumEt100Uturnon->SetLineColor(6);
  SumEt100Uturnon->SetMarkerColor(6);

  SumEtTurnOnCurves->Add(SumEt60Uturnon ,"lp");
  SumEtTurnOnCurves->Add(SumEt100Uturnon ,"lp");
  leg->AddEntry(SumEt60Uturnon,"ETT60","lP");
  leg->AddEntry(SumEt100Uturnon,"ETT100","lP");
  SumEtTurnOnCurves->Draw("a p");
  SumEtTurnOnCurves->GetXaxis()->SetTitle("E_{T} GeV");
  SumEtTurnOnCurves->GetYaxis()->SetTitle("Efficiency");


  leg->Draw();
  c1->Write();
  c1->cd();
  c1->Clear();
  leg->Clear();
  TMultiGraph *METTurnOnCurves = new TMultiGraph("Met Turn On curves","Met Turn on curves");

  TGraphAsymmErrors *MET_70UTurnOn = new TGraphAsymmErrors();
  TGraphAsymmErrors *MET_30UTurnOn = new TGraphAsymmErrors();
  TGraphAsymmErrors *MET_20UTurnOn = new TGraphAsymmErrors();
  TGraphAsymmErrors *MET_12UTurnOn = new TGraphAsymmErrors();


  MET_70UTurnOn->BayesDivide(MET_70U, METReference);
  MET_70UTurnOn->SetMarkerStyle(20);
  MET_70UTurnOn->SetLineColor(2);
  MET_70UTurnOn->SetMarkerColor(2);
  MET_30UTurnOn->BayesDivide(MET_30U, METReference);
  MET_30UTurnOn->SetMarkerStyle(21);
  MET_30UTurnOn->SetLineColor(3);
  MET_30UTurnOn->SetMarkerColor(3);
  MET_20UTurnOn->BayesDivide(MET_20U, METReference);
  MET_20UTurnOn->SetMarkerStyle(22);
  MET_20UTurnOn->SetLineColor(4);
  MET_20UTurnOn->SetMarkerColor(4);
  MET_12UTurnOn->BayesDivide(MET_12U, METReference);
  MET_12UTurnOn->SetMarkerStyle(23);
  MET_12UTurnOn->SetLineColor(46);
  MET_12UTurnOn->SetMarkerColor(46);


  METTurnOnCurves->Add(MET_70UTurnOn ,"lp");
  METTurnOnCurves->Add(MET_30UTurnOn ,"lp");
  METTurnOnCurves->Add(MET_20UTurnOn ,"lp");
  METTurnOnCurves->Add(MET_12UTurnOn ,"lp");
  leg->AddEntry(MET_12UTurnOn,"MET12","lP");
  leg->AddEntry(MET_20UTurnOn,"MET20","lP");
  leg->AddEntry(MET_30UTurnOn,"MET30","lP");
  leg->AddEntry(MET_70UTurnOn,"MET70","lP");
 gPad->SetGridx(); gPad->SetGridy();
  METTurnOnCurves->Draw("a p");
  METTurnOnCurves->GetXaxis()->SetTitle("MET GeV");
  METTurnOnCurves->GetYaxis()->SetTitle("Efficiency");
  leg->Draw();
  c1->Write();
  c1->cd();
  c1->Clear();
  leg->Clear();


  TMultiGraph *MHTTurnOnCurves = new TMultiGraph("MHT Turn on curves", " MHT Turn On curves");
  TGraphAsymmErrors *MHT_30UTurnOn = new TGraphAsymmErrors();
  TGraphAsymmErrors *MHT_20UTurnOn = new TGraphAsymmErrors();

  MHT_30UTurnOn->BayesDivide(MHT_30U, MHTReference);
  MHT_30UTurnOn->SetMarkerStyle(20);
  MHT_30UTurnOn->SetLineColor(2);
  MHT_30UTurnOn->SetMarkerColor(2);
  MHT_20UTurnOn->BayesDivide(MHT_20U, MHTReference);
  MHT_20UTurnOn->SetMarkerStyle(21);
  MHT_20UTurnOn->SetLineColor(3);
  MHT_20UTurnOn->SetMarkerColor(3);

  MHTTurnOnCurves->Add(MHT_20UTurnOn ,"lp");
  MHTTurnOnCurves->Add(MHT_30UTurnOn ,"lp");
  leg->AddEntry(MHT_20UTurnOn,"MHT20","lP");
  leg->AddEntry(MHT_30UTurnOn,"MHT30","lP");
  gPad->SetGridx(); gPad->SetGridy();
  MHTTurnOnCurves->Draw("a p");
  MHTTurnOnCurves->GetXaxis()->SetTitle("MHT GeV");
  MHTTurnOnCurves->GetYaxis()->SetTitle("Efficiency");


  leg->Draw();
  c1->Write();
  c1->cd();
  c1->Clear();
  leg->Clear();

MHT_30U->Write();
MHT_20U->Write();
MET_70U->Write();
MET_30U->Write();
MET_20U->Write();
MET_12U->Write();
SumEt_100U->Write();
SumEt_60U->Write();
HT_200U->Write();
HT_100U->Write();
HT_75U->Write();
HT_75U_Bit->Write();
HT_50U->Write();
METReference->Write();
MHTReference->Write();
SumEtReference->Write();
HTReference->Write();
L1Ht ->Write();
L1mHt->Write();
L1Et ->Write();
L1mEt->Write();



  theFile->Write();
  theFile->Close();


}
