#include "./L1JetAnalysis.hh"
// --------------------------------------------------------------------
//                       L1JetAnalysis macro definition
//
//    macro automatically generated by GenerateMacro.sh script
//    author           : bm409
//    creation date    : Sat Oct 23 14:00:25 CEST 2010
//    last update date :
//    description      :
//
// --------------------------------------------------------------------


// --------------------------------------------------------------------
//                             run function
// --------------------------------------------------------------------

void L1JetAnalysis::BookHistos() {

  RefJets = new TH1F("RefJet", "RefJetEt",1000,0.,1000);
  Bit15   = new TH1F("Bit15", "JetEt",1000,0.,1000);
  Bit16   = new TH1F("Bit16", "JetEt",1000,0.,1000);
  Bit17   = new TH1F("Bit17", "JetEt",1000,0.,1000);
  Bit18   = new TH1F("Bit18", "JetEt",1000,0.,1000);
  Bit19   = new TH1F("Bit19", "JetEt",1000,0.,1000);
  Bit20   = new TH1F("Bit20", "JetEt",1000,0.,1000);
  Bit21   = new TH1F("Bit21", "JetEt",1000,0.,1000);
  l1JetEn = new TH1F("L1Energy", "L1Et",1000,0.,1000.);
  l1Jet0 = new TH1F( "l1Jet0", "L1Et",1000,0.,1000.);
  l1Jet1 = new TH1F( "l1Jet1", "L1Et",1000,0.,1000.);
  l1Jet2 = new TH1F( "l1Jet2", "L1Et",1000,0.,1000.);
  l1Jet3 = new TH1F( "l1Jet3", "L1Et",1000,0.,1000.);
  l1Jet4 = new TH1F( "l1Jet4", "L1Et",1000,0.,1000.);
  l1Jet5 = new TH1F( "l1Jet5", "L1Et",1000,0.,1000.);
  dR = new TH1F( "DeltaR", "#delta R", 60,0.,3.2);
  RecoHTL1100 = new TH1F( "RecoHTL1100", "HT",1000,0.,1000.);
  RecoHTL1150 = new TH1F( "RecoHTL1150", "HT",1000,0.,1000.);
  RecoHTL150 = new TH1F( "RecoHTL150", "HT",1000,0.,1000.);
  RecoHT = new TH1F( "RecoHT", "HT",1000,0.,1000.);
  recoJetCorrelation = new TH2F( "RecoJetEtvsUnCorRecoJetEt",";Et(UnCorr);Et(Corr)",100,0.,500.,100,0.,500.);
// CandidateJets30Gev = new TH1F("RefJet", "RefJetEt",200,0.,1000);
  RecoVsl1HFE       = new TH2F(     "RecoVsl1HFE",    "Offline Uncorrected Jet Et; L1 Jet Et",1000,0.,1000.,250,0.,1000);
  ResolutionEtHFE   = new TH2F( "ResolutionEtHFE","RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  ResolutionHFE     = new TH1F(   "ResolutionHFE",  "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  RecoVsl1HFH       = new TH2F(     "RecoVsl1HFH",    "Offline Uncorrected Jet Et; L1 Jet Et",250,0.,1000.,250,0.,1000);
  ResolutionEtHFH   = new TH2F( "ResolutionEtHFH","RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  ResolutionHFH     = new TH1F(   "ResolutionHFH",  "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  ResolutionHE      = new TH1F(    "ResolutionHE",   "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  ResolutionEtHE    = new TH2F(  "ResolutionEtHE", "RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  RecoVsl1HE        = new TH2F(      "RecoVsl1HE",     "Offline Uncorrected Jet Et; L1 Jet Et",250,0.,1000.,250,0.,1000);
  ResolutionEE      = new TH1F(    "ResolutionEE",   "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  ResolutionEtEE    = new TH2F(  "ResolutionEtEE", "RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  RecoVsl1EE        = new TH2F(      "RecoVsl1EE",     "Offline Uncorrected Jet Et; L1 Jet Et",250,0.,1000.,250,0.,1000);
  ResolutionHB      = new TH1F(    "ResolutionHB",   "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  ResolutionEtHB    = new TH2F(  "ResolutionEtHB", "RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  RecoVsl1HB        = new TH2F(      "RecoVsl1HB",     "Offline Uncorrected Jet Et; L1 Jet Et",250,0.,1000.,250,0.,1000);
  ResolutionEB      = new TH1F(    "ResolutionEB",   "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  ResolutionEtEB    = new TH2F(  "ResolutionEtEB", "RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  RecoVsl1EB        = new TH2F(      "RecoVsl1EB",     "Offline Uncorrected Jet Et; L1 Jet Et",250,0.,1000.,250,0.,1000);
  EnCorrelation     = new TH2F(   "EnCorrelation", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  L1CorVsUnCor      = new TH2F("L1CorVsUnCor", ";L1Corrected;L1UnCOrrected",63,0.,252.,63,0.,252.);
  EMF               = new TH1F(  "EMF","Jet[0] FEM",100,-1.,1.);
  timeMap           = new TH2I("Bits", "Bunch Crossing vs trigger bit", 130, 0., 130., 10, 0., 10.);
  ResolutionAsFnOfpT = new TH2F("ResolutionAsFnOfpT"," ; L1 P_{T};(Reco Jet Et - L1 Jet Et) / Reco Jet Et",30,0.,300.,200,-10.,10.);
  ResolutionAsFnOfeta = new TH2F("ResolutionAsFnOfeta"," ; L1 #eta;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",20,-5.,5.,200,-10.,10.);
  L1HtRecoJetCorrelation     = new TH2F(   "L1HtRecoJetCorrelation", ";RecoJetEt;L1Ht",250,0.,1000.,250,0.,1000.);
  MEtCorrelation     = new TH2F(   "MEtCorrelation", ";Reco MET;L1MET",250,0.,1000.,250,0.,1000.);
  double etabins[23] = {
      -5.000,
      -4.500,
      -4.000,
      -3.500,
      -3.000,
      -2.172,
      -1.740,
      -1.392,
      -1.044,
      -0.695,
      -0.348,
      0.000,
      0.348,
      0.695,
      1.044,
      1.392,
      1.740,
      2.172,
      3.000,
      3.500,
      4.000,
      4.500,
      5.000};
    L1EtaPhiMap = new TH2D("etaPhiMap","h2" ,22,etabins, 18, -1*TMath::Pi()-0.5, TMath::Pi()-0.5);




  }

// --------------------------------------------------------------------
//                             run function
// --------------------------------------------------------------------
  void L1JetAnalysis::run(Long64_t nevents, TString outputname, TString TriggerBit) //To run use m.run(events,"SomeoutputName","HLT TriggerName") (leave HLT name as white space to select no trigger)
  {
    //Book Histos
    BookHistos();
    //load TDR style
    TFile *theFile = new TFile(outputname, "RECREATE");
    theFile->cd();
    //number of events to process
    if (nevents==-1 || nevents>GetEntries()) nevents=GetEntries();
    std::cout << nevents  << " to process ..." << std::endl;
    //loop over the events
    for (Long64_t i= 0; i<   nevents; i++)
    {
      //load the i-th event
      double RecoJetThreshold = 10.;
      Long64_t ientry = LoadTree(i); if (ientry < 0) break;
      GetEntry(i);
      //process progress
      if( i!=0 && ( i%1 ) ==0 ) {std::cout << "- processing event " << i << "\r" << std::flush;}
      double wgt =1.0;
      // Check that we have jets in the event.
      if((recoJet_->et).size() < 1) continue;
      // Trigger stuff
      if (!TriggerBit.IsWhitespace() && !PassHLT(TriggerBit) ) continue;
      // if (!PassTrig(1040,2)) continue ;
      // Selection for the turn on curves
      // Note as corrected jets are no longer listed in pt order we now have to find the leading jet
      // Makeshift ENUms
      int Et = 1;
      int Eta = 2;
      int Phi = 3;

      int leadJet = leadingOfflineJet();
      recoJetCorrelation->Fill(recoJet_->et[leadJet],recoJet_->etCorr[leadJet],wgt);
      if(l1extra_->cenJetEt.size() > 0 && l1extra_->cenJetEt.size() > 0){  L1CorVsUnCor->Fill(l1extra_->cenJetEt[0],l1extra_->cenJetEt[0]);}



      //  Require only jets MatchedEmu to a L1 Jet
      if ( !MatchEmuJet(leadJet) ) continue; // only select events with a MatchedEmu jet, good for resolution stides but not eff
      //  NB a bit of a hack to read out the correct value from the ReturnMatchedEmuQuantity function -- Didnt know about Enums at the time, will re-write when there is time
      std::pair <int,int> MatchedEmuJet = ReturnMatchedEmuJet(leadJet); // Try to match a L1 Jet to the zeroth reco Jet, return the l1 type and l1 index of
      if(ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 250. ) continue;


      if(recoJet_->etCorr[leadJet]> RecoJetThreshold && fabs(recoJet_->eta[leadJet])< 3.0 && LooseID(leadJet) ){ // check leading recoJet is with in
        dR->Fill(deltaR(recoJet_->eta[leadJet], recoJet_->phi[leadJet], ReturnMatchedEmuQuantity(MatchedEmuJet,Eta), ReturnMatchedEmuQuantity(MatchedEmuJet,Phi)),wgt);
        EnCorrelation->Fill(recoJet_->etCorr[leadJet],ReturnMatchedEmuQuantity(MatchedEmuJet,Et),wgt);
        L1HtRecoJetCorrelation->Fill(recoJet_->etCorr[leadJet],l1extra_->ht,wgt);
        MEtCorrelation->Fill(recoMet_->met,l1extra_->met,wgt);
        L1EtaPhiMap->Fill(ReturnMatchedEmuQuantity(MatchedEmuJet,Eta),ReturnMatchedEmuQuantity(MatchedEmuJet,Phi),wgt);
        l1JetEn->Fill(ReturnMatchedEmuQuantity(MatchedEmuJet,Et),wgt);
        RefJets->Fill(recoJet_->etCorr[leadJet],wgt); // Denominator for turn on curves

        // Ask for Corrected L1 Jets -- Use on 2011 Data
        if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 16.){
          Bit15->Fill(recoJet_->etCorr[leadJet],wgt);
          l1Jet0->Fill(ReturnMatchedEmuQuantity(MatchedEmuJet,Et),wgt);
        } // now goes to SingleJet16
        if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 20.){
          Bit16->Fill(recoJet_->etCorr[leadJet],wgt);
          l1Jet1->Fill(ReturnMatchedEmuQuantity(MatchedEmuJet,Et),wgt);
        } // now goes to SingleJet36
        if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 36.){
          Bit17->Fill(recoJet_->etCorr[leadJet],wgt);
          l1Jet2->Fill(ReturnMatchedEmuQuantity(MatchedEmuJet,Et),wgt);
        } // now goes to SingleJet52
        if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 52.){
          Bit18->Fill(recoJet_->etCorr[leadJet],wgt);
          l1Jet3->Fill(ReturnMatchedEmuQuantity(MatchedEmuJet,Et),wgt);
        } // now goes to SingleJet68
        if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 68.){
          Bit19->Fill(recoJet_->etCorr[leadJet],wgt);
          l1Jet4->Fill(ReturnMatchedEmuQuantity(MatchedEmuJet,Et),wgt);
        } // now goes to SingleJet92
        if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 92.){
          Bit20->Fill(recoJet_->etCorr[leadJet],wgt);
          l1Jet5->Fill(ReturnMatchedEmuQuantity(MatchedEmuJet,Et),wgt);
        } // now goes to SingleJet128
        if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 128.){
          Bit21->Fill(recoJet_->etCorr[leadJet],wgt);
        } // now goes to SingleJet128

      }

    //Make a plot of the 0th L1 Jet energy

    // Note that for the resolution studies we can use more than the leading jet -- enter different loop
        for(size_t j = 0 ; j < recoJet_->etCorr.size(); ++j)
         {
           if ( !LooseID(j) ) continue;
           if( MatchJet(j) ){
            if( recoJet_->etCorr[j] < RecoJetThreshold ) continue;
             // barrel jets
             std::pair <int,int> MatchedEmuJetLoop = ReturnMatchedEmuJet(j); // Try to match a L1 Jet to the jth reco Jet, return the l1 type and index of L1Jet
              if(ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et) > 250. ) continue;
             EMF->Fill(recoJet_->eEMF[j],2);
             ResolutionAsFnOfeta->Fill(recoJet_->eta[j], (recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
             ResolutionAsFnOfpT->Fill(recoJet_->etCorr[j], (recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);

             if( fabs(recoJet_->eta[j]) < 1.3 ){
               if(recoJet_->eEMF[j] > 0.9){
                 RecoVsl1EB->Fill(recoJet_->etCorr[j],ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et),wgt);
                 ResolutionEtEB->Fill(recoJet_->etCorr[j], (recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
                 ResolutionEB->Fill((recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
               }
               if(recoJet_->eEMF[j] < 0.4){
                 RecoVsl1HB->Fill(recoJet_->etCorr[j],ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et),wgt);
                 ResolutionEtHB->Fill(recoJet_->etCorr[j], (recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
                 ResolutionHB->Fill((recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
               }
             }
                 //endcap jets
             if(fabs(recoJet_->eta[j]) > 1.3 && fabs(recoJet_->eta[j]) < 3.0){
               if(recoJet_->eEMF[j] > 0.9){
                 RecoVsl1EE->Fill(recoJet_->etCorr[j],ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et),wgt);
                 ResolutionEtEE->Fill(recoJet_->etCorr[j], (recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
                 ResolutionEE->Fill((recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
               }
               if(recoJet_->eEMF[j] < 0.4){
                 RecoVsl1HE->Fill(recoJet_->etCorr[j],ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et),wgt);
                 ResolutionEtHE->Fill(recoJet_->etCorr[j], (recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
                 ResolutionHE->Fill((recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
               }

             }
         //forward jets
             if(fabs(recoJet_->eta[j]) > 3.0 ){
               if(recoJet_->eEMF[j] > 0.9){
                 RecoVsl1HFE->Fill(recoJet_->etCorr[j],ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et),wgt);
                 ResolutionEtHFE->Fill(recoJet_->etCorr[j], (recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
                 ResolutionHFE->Fill((recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
               }
               if(recoJet_->eEMF[j] < 0.4){
                 RecoVsl1HFH->Fill(recoJet_->etCorr[j],ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et),wgt);
                 ResolutionEtHFH->Fill(recoJet_->etCorr[j], (recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
                 ResolutionHFH->Fill((recoJet_->etCorr[j]-ReturnMatchedEmuQuantity(MatchedEmuJetLoop,Et))/recoJet_->etCorr[j],wgt);
               }

             }

           }
         }


    // Timing studies
      for(size_t bx = 0; bx < 5; ++bx)
      {
        for(size_t bit = 0; bit < 128; ++bit)
        {
          if(PassTrig(bit,bx)){
            timeMap->Fill(bit,bx,wgt);
          }
        }
      }
  // cout << " _____________________ END EVENT ___________________" << endl;

    }
    //  Write out the files so we can make eff curves etc - do this outside of the macro so we can run on the batch
    timeMap->Write();
    ResolutionHE->Write();
    ResolutionEtHE->Write();
    RecoVsl1HE->Write();
    ResolutionEE->Write();
    ResolutionEtEE->Write();
    RecoVsl1EE->Write();
    ResolutionHB->Write();
    ResolutionEtHB->Write();
    RecoVsl1HB->Write();
    ResolutionEB->Write();
    ResolutionEtEB->Write();
    RecoVsl1EB->Write();
    EMF->Write();
    ResolutionHFH->Write();
    ResolutionEtHFH->Write();
    RecoVsl1HFH->Write();
    ResolutionHFE->Write();
    ResolutionEtHFE->Write();
    RecoVsl1HFE->Write();
    Bit15->Write();
    Bit16->Write();
    Bit17->Write();
    Bit18->Write();
    Bit19->Write();
    Bit20->Write();
    Bit21->Write();
    RefJets->Write();
    ResolutionAsFnOfpT->Write();
    ResolutionAsFnOfeta->Write();
    l1JetEn->Write();
    l1Jet0->Write();
    l1Jet1->Write();
    l1Jet2->Write();
    l1Jet3->Write();
    l1Jet4->Write();
    l1Jet5->Write();
    L1EtaPhiMap->Write();
    EnCorrelation->Write();
    MEtCorrelation->Write();
    L1HtRecoJetCorrelation->Write();
    dR->Write();
    recoJetCorrelation->Write();
    RecoHTL1100->Write();
    RecoHTL1150->Write();
    RecoHTL1150->Write();
    RecoHTL150->Write();
    L1CorVsUnCor->Write();
    // Write and close the file!
    theFile->Write();
    theFile->Close();
  }
