#include "L1Ntuple.h"
#include "hist.C"
#include "Style.C"

// --------------------------------------------------------------------
//                       testMacro macro definition
//
//    macro automatically generated by GenerateMacro.sh script
//    author           : bm409
//    creation date    : Sat Oct 23 13:57:06 CEST 2010
//    last update date :
//    description      :
//
// --------------------------------------------------------------------

class testMacro : public L1Ntuple
{
  public :

    //constructor
    testMacro(std::string filename) : L1Ntuple(filename) {}
    testMacro() {}
    ~testMacro() {}

    //main function macro : arguments can be adpated to your need
    void run(Long64_t nevents);

  private :

    //your private methods can be declared here
};


// --------------------------------------------------------------------
//                             run function
// --------------------------------------------------------------------
void testMacro::run(Long64_t nevents)
{
  //load TDR style
  setTDRStyle();

  //number of events to process
  if (nevents==-1 || nevents>GetEntries()) nevents=GetEntries();
  std::cout << nevents << " to process ..." << std::endl;

  //loop over the events
  for (Long64_t i=0; i<nevents; i++)
    {
      //load the i-th event
      Long64_t ientry = LoadTree(i); if (ientry < 0) break;
      GetEntry(i);

      //process progress
      if(i!=0 && (i%10000)==0)
  std::cout << "- processing event " << i << "\r" << std::flush;
          cout  << "Event "<< i <<" recoJet->et.size() = " << recoJet_->et.size() << endl;



      //write your code here

    }
}
